language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -U codeclimate-test-reporter
script:
  - coverage run ./manage.py test
after_success: codeclimate-test-reporter
