language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script_before: 
  - python manage.py makemigrations 
  - python manage.py migrate 
script: 
  - python manage.py test