# Generated by Django 2.0.2 on 2018-08-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180618_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ref_author',
        ),
        migrations.AddField(
            model_name='book',
            name='ref_author',
            field=models.ManyToManyField(to='book.Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='ref_category',
        ),
        migrations.AddField(
            model_name='book',
            name='ref_category',
            field=models.ManyToManyField(to='book.Category'),
        ),
    ]
