# Generated by Django 2.0.2 on 2018-08-26 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='ref_user',
        ),
        migrations.AddField(
            model_name='workspace',
            name='ref_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_auth.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
