# Generated by Django 2.0.2 on 2018-08-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_auth', '0002_auto_20180826_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workspace_active',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
