# Generated by Django 2.0.2 on 2018-09-01 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_auth', '0005_remove_profile_workspace_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
