# Generated by Django 2.0.2 on 2018-09-01 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_auth', '0006_auto_20180901_2313'),
        ('record', '0003_auto_20180826_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='ref_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system_auth.Profile'),
        ),
    ]
