# Generated by Django 2.0.2 on 2018-09-02 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_auth', '0006_auto_20180901_2313'),
        ('record', '0005_historyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='ref_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system_auth.Workspace'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='record.StatusRecord'),
        ),
    ]
